// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_HARDWARE_API_G_H_
#define PIGEON_HARDWARE_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace nexora_sdk {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Generated class from Pigeon that represents data sent in messages.
class NexoraCameraOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraCameraOptions();

  // Constructs an object setting all fields.
  explicit NexoraCameraOptions(
    const std::string* resolution,
    const std::string* focus_mode,
    const std::string* exposure_mode,
    const double* exposure_compensation,
    const bool* mirror_front_camera);

  const std::string* resolution() const;
  void set_resolution(const std::string_view* value_arg);
  void set_resolution(std::string_view value_arg);

  const std::string* focus_mode() const;
  void set_focus_mode(const std::string_view* value_arg);
  void set_focus_mode(std::string_view value_arg);

  const std::string* exposure_mode() const;
  void set_exposure_mode(const std::string_view* value_arg);
  void set_exposure_mode(std::string_view value_arg);

  const double* exposure_compensation() const;
  void set_exposure_compensation(const double* value_arg);
  void set_exposure_compensation(double value_arg);

  const bool* mirror_front_camera() const;
  void set_mirror_front_camera(const bool* value_arg);
  void set_mirror_front_camera(bool value_arg);

  bool operator==(const NexoraCameraOptions& other) const;
  bool operator!=(const NexoraCameraOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraCameraOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> resolution_;
  std::optional<std::string> focus_mode_;
  std::optional<std::string> exposure_mode_;
  std::optional<double> exposure_compensation_;
  std::optional<bool> mirror_front_camera_;
};


// Generated class from Pigeon that represents data sent in messages.
class CustomClassifierOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  CustomClassifierOptions();

  // Constructs an object setting all fields.
  explicit CustomClassifierOptions(
    const std::string* model_asset_path,
    const ::flutter::EncodableList* labels,
    const double* threshold);

  const std::string* model_asset_path() const;
  void set_model_asset_path(const std::string_view* value_arg);
  void set_model_asset_path(std::string_view value_arg);

  const ::flutter::EncodableList* labels() const;
  void set_labels(const ::flutter::EncodableList* value_arg);
  void set_labels(const ::flutter::EncodableList& value_arg);

  const double* threshold() const;
  void set_threshold(const double* value_arg);
  void set_threshold(double value_arg);

  bool operator==(const CustomClassifierOptions& other) const;
  bool operator!=(const CustomClassifierOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static CustomClassifierOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> model_asset_path_;
  std::optional<::flutter::EncodableList> labels_;
  std::optional<double> threshold_;
};


// Generated class from Pigeon that represents data sent in messages.
class VisionModeOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  VisionModeOptions();

  // Constructs an object setting all fields.
  explicit VisionModeOptions(
    const bool* barcode,
    const bool* face);

  const bool* barcode() const;
  void set_barcode(const bool* value_arg);
  void set_barcode(bool value_arg);

  const bool* face() const;
  void set_face(const bool* value_arg);
  void set_face(bool value_arg);

  bool operator==(const VisionModeOptions& other) const;
  bool operator!=(const VisionModeOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static VisionModeOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> barcode_;
  std::optional<bool> face_;
};


// Generated class from Pigeon that represents data sent in messages.
class BasicAudioOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  BasicAudioOptions();

  // Constructs an object setting all fields.
  explicit BasicAudioOptions(
    const bool* enable_f_f_t,
    const bool* stream_bytes,
    const int64_t* update_interval_ms);

  const bool* enable_f_f_t() const;
  void set_enable_f_f_t(const bool* value_arg);
  void set_enable_f_f_t(bool value_arg);

  const bool* stream_bytes() const;
  void set_stream_bytes(const bool* value_arg);
  void set_stream_bytes(bool value_arg);

  const int64_t* update_interval_ms() const;
  void set_update_interval_ms(const int64_t* value_arg);
  void set_update_interval_ms(int64_t value_arg);

  bool operator==(const BasicAudioOptions& other) const;
  bool operator!=(const BasicAudioOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static BasicAudioOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> enable_f_f_t_;
  std::optional<bool> stream_bytes_;
  std::optional<int64_t> update_interval_ms_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraAudioOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraAudioOptions();

  // Constructs an object setting all fields.
  explicit NexoraAudioOptions(
    const int64_t* sample_rate,
    const std::string* channels,
    const bool* enable_echo_cancellation,
    const bool* enable_noise_suppression);

  const int64_t* sample_rate() const;
  void set_sample_rate(const int64_t* value_arg);
  void set_sample_rate(int64_t value_arg);

  const std::string* channels() const;
  void set_channels(const std::string_view* value_arg);
  void set_channels(std::string_view value_arg);

  const bool* enable_echo_cancellation() const;
  void set_enable_echo_cancellation(const bool* value_arg);
  void set_enable_echo_cancellation(bool value_arg);

  const bool* enable_noise_suppression() const;
  void set_enable_noise_suppression(const bool* value_arg);
  void set_enable_noise_suppression(bool value_arg);

  bool operator==(const NexoraAudioOptions& other) const;
  bool operator!=(const NexoraAudioOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraAudioOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> sample_rate_;
  std::optional<std::string> channels_;
  std::optional<bool> enable_echo_cancellation_;
  std::optional<bool> enable_noise_suppression_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraLocationOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraLocationOptions();

  // Constructs an object setting all fields.
  explicit NexoraLocationOptions(
    const std::string* accuracy,
    const double* distance_filter,
    const int64_t* interval_ms);

  const std::string* accuracy() const;
  void set_accuracy(const std::string_view* value_arg);
  void set_accuracy(std::string_view value_arg);

  const double* distance_filter() const;
  void set_distance_filter(const double* value_arg);
  void set_distance_filter(double value_arg);

  const int64_t* interval_ms() const;
  void set_interval_ms(const int64_t* value_arg);
  void set_interval_ms(int64_t value_arg);

  bool operator==(const NexoraLocationOptions& other) const;
  bool operator!=(const NexoraLocationOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraLocationOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> accuracy_;
  std::optional<double> distance_filter_;
  std::optional<int64_t> interval_ms_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraSensorOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraSensorOptions();

  // Constructs an object setting all fields.
  explicit NexoraSensorOptions(const int64_t* frequency_hz);

  const int64_t* frequency_hz() const;
  void set_frequency_hz(const int64_t* value_arg);
  void set_frequency_hz(int64_t value_arg);

  bool operator==(const NexoraSensorOptions& other) const;
  bool operator!=(const NexoraSensorOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraSensorOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> frequency_hz_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraBiometricOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraBiometricOptions();

  // Constructs an object setting all fields.
  explicit NexoraBiometricOptions(
    const std::string* title,
    const std::string* subtitle,
    const std::string* description,
    const std::string* negative_button_text);

  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  const std::string* subtitle() const;
  void set_subtitle(const std::string_view* value_arg);
  void set_subtitle(std::string_view value_arg);

  const std::string* description() const;
  void set_description(const std::string_view* value_arg);
  void set_description(std::string_view value_arg);

  const std::string* negative_button_text() const;
  void set_negative_button_text(const std::string_view* value_arg);
  void set_negative_button_text(std::string_view value_arg);

  bool operator==(const NexoraBiometricOptions& other) const;
  bool operator!=(const NexoraBiometricOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraBiometricOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> title_;
  std::optional<std::string> subtitle_;
  std::optional<std::string> description_;
  std::optional<std::string> negative_button_text_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraBluetoothScanOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraBluetoothScanOptions();

  // Constructs an object setting all fields.
  explicit NexoraBluetoothScanOptions(
    const ::flutter::EncodableList* service_uuids,
    const std::string* scan_mode);

  const ::flutter::EncodableList* service_uuids() const;
  void set_service_uuids(const ::flutter::EncodableList* value_arg);
  void set_service_uuids(const ::flutter::EncodableList& value_arg);

  const std::string* scan_mode() const;
  void set_scan_mode(const std::string_view* value_arg);
  void set_scan_mode(std::string_view value_arg);

  bool operator==(const NexoraBluetoothScanOptions& other) const;
  bool operator!=(const NexoraBluetoothScanOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraBluetoothScanOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<::flutter::EncodableList> service_uuids_;
  std::optional<std::string> scan_mode_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraStorageInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraStorageInfo();

  // Constructs an object setting all fields.
  explicit NexoraStorageInfo(
    const int64_t* internal_total,
    const int64_t* internal_free,
    const int64_t* external_total,
    const int64_t* external_free,
    const int64_t* app_cache_size,
    const int64_t* app_data_size);

  const int64_t* internal_total() const;
  void set_internal_total(const int64_t* value_arg);
  void set_internal_total(int64_t value_arg);

  const int64_t* internal_free() const;
  void set_internal_free(const int64_t* value_arg);
  void set_internal_free(int64_t value_arg);

  const int64_t* external_total() const;
  void set_external_total(const int64_t* value_arg);
  void set_external_total(int64_t value_arg);

  const int64_t* external_free() const;
  void set_external_free(const int64_t* value_arg);
  void set_external_free(int64_t value_arg);

  const int64_t* app_cache_size() const;
  void set_app_cache_size(const int64_t* value_arg);
  void set_app_cache_size(int64_t value_arg);

  const int64_t* app_data_size() const;
  void set_app_data_size(const int64_t* value_arg);
  void set_app_data_size(int64_t value_arg);

  bool operator==(const NexoraStorageInfo& other) const;
  bool operator!=(const NexoraStorageInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraStorageInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<int64_t> internal_total_;
  std::optional<int64_t> internal_free_;
  std::optional<int64_t> external_total_;
  std::optional<int64_t> external_free_;
  std::optional<int64_t> app_cache_size_;
  std::optional<int64_t> app_data_size_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraFileInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraFileInfo();

  // Constructs an object setting all fields.
  explicit NexoraFileInfo(
    const std::string* name,
    const int64_t* size,
    const bool* is_directory,
    const int64_t* last_modified_ms);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const int64_t* size() const;
  void set_size(const int64_t* value_arg);
  void set_size(int64_t value_arg);

  const bool* is_directory() const;
  void set_is_directory(const bool* value_arg);
  void set_is_directory(bool value_arg);

  const int64_t* last_modified_ms() const;
  void set_last_modified_ms(const int64_t* value_arg);
  void set_last_modified_ms(int64_t value_arg);

  bool operator==(const NexoraFileInfo& other) const;
  bool operator!=(const NexoraFileInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraFileInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> name_;
  std::optional<int64_t> size_;
  std::optional<bool> is_directory_;
  std::optional<int64_t> last_modified_ms_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraDeviceInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraDeviceInfo();

  // Constructs an object setting all fields.
  explicit NexoraDeviceInfo(
    const std::string* platform,
    const std::string* manufacturer,
    const std::string* model,
    const std::string* os_version,
    const std::string* sdk_version,
    const bool* is_physical_device,
    const int64_t* total_ram_bytes,
    const int64_t* available_ram_bytes,
    const std::string* cpu_architecture,
    const double* screen_refresh_rate,
    const std::string* thermal_state);

  const std::string* platform() const;
  void set_platform(const std::string_view* value_arg);
  void set_platform(std::string_view value_arg);

  const std::string* manufacturer() const;
  void set_manufacturer(const std::string_view* value_arg);
  void set_manufacturer(std::string_view value_arg);

  const std::string* model() const;
  void set_model(const std::string_view* value_arg);
  void set_model(std::string_view value_arg);

  const std::string* os_version() const;
  void set_os_version(const std::string_view* value_arg);
  void set_os_version(std::string_view value_arg);

  const std::string* sdk_version() const;
  void set_sdk_version(const std::string_view* value_arg);
  void set_sdk_version(std::string_view value_arg);

  const bool* is_physical_device() const;
  void set_is_physical_device(const bool* value_arg);
  void set_is_physical_device(bool value_arg);

  const int64_t* total_ram_bytes() const;
  void set_total_ram_bytes(const int64_t* value_arg);
  void set_total_ram_bytes(int64_t value_arg);

  const int64_t* available_ram_bytes() const;
  void set_available_ram_bytes(const int64_t* value_arg);
  void set_available_ram_bytes(int64_t value_arg);

  const std::string* cpu_architecture() const;
  void set_cpu_architecture(const std::string_view* value_arg);
  void set_cpu_architecture(std::string_view value_arg);

  const double* screen_refresh_rate() const;
  void set_screen_refresh_rate(const double* value_arg);
  void set_screen_refresh_rate(double value_arg);

  const std::string* thermal_state() const;
  void set_thermal_state(const std::string_view* value_arg);
  void set_thermal_state(std::string_view value_arg);

  bool operator==(const NexoraDeviceInfo& other) const;
  bool operator!=(const NexoraDeviceInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraDeviceInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> platform_;
  std::optional<std::string> manufacturer_;
  std::optional<std::string> model_;
  std::optional<std::string> os_version_;
  std::optional<std::string> sdk_version_;
  std::optional<bool> is_physical_device_;
  std::optional<int64_t> total_ram_bytes_;
  std::optional<int64_t> available_ram_bytes_;
  std::optional<std::string> cpu_architecture_;
  std::optional<double> screen_refresh_rate_;
  std::optional<std::string> thermal_state_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraConnectivityInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraConnectivityInfo();

  // Constructs an object setting all fields.
  explicit NexoraConnectivityInfo(
    const bool* is_connected,
    const std::string* network_type,
    const bool* is_metered,
    const bool* is_vpn,
    const int64_t* signal_strength,
    const std::string* ip_address);

  const bool* is_connected() const;
  void set_is_connected(const bool* value_arg);
  void set_is_connected(bool value_arg);

  const std::string* network_type() const;
  void set_network_type(const std::string_view* value_arg);
  void set_network_type(std::string_view value_arg);

  const bool* is_metered() const;
  void set_is_metered(const bool* value_arg);
  void set_is_metered(bool value_arg);

  const bool* is_vpn() const;
  void set_is_vpn(const bool* value_arg);
  void set_is_vpn(bool value_arg);

  const int64_t* signal_strength() const;
  void set_signal_strength(const int64_t* value_arg);
  void set_signal_strength(int64_t value_arg);

  const std::string* ip_address() const;
  void set_ip_address(const std::string_view* value_arg);
  void set_ip_address(std::string_view value_arg);

  bool operator==(const NexoraConnectivityInfo& other) const;
  bool operator!=(const NexoraConnectivityInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraConnectivityInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> is_connected_;
  std::optional<std::string> network_type_;
  std::optional<bool> is_metered_;
  std::optional<bool> is_vpn_;
  std::optional<int64_t> signal_strength_;
  std::optional<std::string> ip_address_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraBatteryInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraBatteryInfo();

  // Constructs an object setting all fields.
  explicit NexoraBatteryInfo(
    const double* level,
    const bool* is_charging,
    const std::string* status,
    const double* temperature);

  const double* level() const;
  void set_level(const double* value_arg);
  void set_level(double value_arg);

  const bool* is_charging() const;
  void set_is_charging(const bool* value_arg);
  void set_is_charging(bool value_arg);

  const std::string* status() const;
  void set_status(const std::string_view* value_arg);
  void set_status(std::string_view value_arg);

  const double* temperature() const;
  void set_temperature(const double* value_arg);
  void set_temperature(double value_arg);

  bool operator==(const NexoraBatteryInfo& other) const;
  bool operator!=(const NexoraBatteryInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraBatteryInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<double> level_;
  std::optional<bool> is_charging_;
  std::optional<std::string> status_;
  std::optional<double> temperature_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraWifiInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraWifiInfo();

  // Constructs an object setting all fields.
  explicit NexoraWifiInfo(
    const std::string* ssid,
    const std::string* bssid,
    const int64_t* signal_strength,
    const int64_t* frequency,
    const int64_t* link_speed);

  const std::string* ssid() const;
  void set_ssid(const std::string_view* value_arg);
  void set_ssid(std::string_view value_arg);

  const std::string* bssid() const;
  void set_bssid(const std::string_view* value_arg);
  void set_bssid(std::string_view value_arg);

  const int64_t* signal_strength() const;
  void set_signal_strength(const int64_t* value_arg);
  void set_signal_strength(int64_t value_arg);

  const int64_t* frequency() const;
  void set_frequency(const int64_t* value_arg);
  void set_frequency(int64_t value_arg);

  const int64_t* link_speed() const;
  void set_link_speed(const int64_t* value_arg);
  void set_link_speed(int64_t value_arg);

  bool operator==(const NexoraWifiInfo& other) const;
  bool operator!=(const NexoraWifiInfo& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraWifiInfo FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> ssid_;
  std::optional<std::string> bssid_;
  std::optional<int64_t> signal_strength_;
  std::optional<int64_t> frequency_;
  std::optional<int64_t> link_speed_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraHapticOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraHapticOptions();

  // Constructs an object setting all fields.
  explicit NexoraHapticOptions(const std::string* type);

  const std::string* type() const;
  void set_type(const std::string_view* value_arg);
  void set_type(std::string_view value_arg);

  bool operator==(const NexoraHapticOptions& other) const;
  bool operator!=(const NexoraHapticOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraHapticOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> type_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraSdkConfig {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraSdkConfig();

  // Constructs an object setting all fields.
  explicit NexoraSdkConfig(
    const bool* enable_logging,
    const bool* eco_mode);

  const bool* enable_logging() const;
  void set_enable_logging(const bool* value_arg);
  void set_enable_logging(bool value_arg);

  const bool* eco_mode() const;
  void set_eco_mode(const bool* value_arg);
  void set_eco_mode(bool value_arg);

  bool operator==(const NexoraSdkConfig& other) const;
  bool operator!=(const NexoraSdkConfig& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraSdkConfig FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<bool> enable_logging_;
  std::optional<bool> eco_mode_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraPermissionStatus {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraPermissionStatus();

  // Constructs an object setting all fields.
  explicit NexoraPermissionStatus(
    const std::string* permission,
    const std::string* state,
    const bool* can_request);

  const std::string* permission() const;
  void set_permission(const std::string_view* value_arg);
  void set_permission(std::string_view value_arg);

  const std::string* state() const;
  void set_state(const std::string_view* value_arg);
  void set_state(std::string_view value_arg);

  const bool* can_request() const;
  void set_can_request(const bool* value_arg);
  void set_can_request(bool value_arg);

  bool operator==(const NexoraPermissionStatus& other) const;
  bool operator!=(const NexoraPermissionStatus& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraPermissionStatus FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> permission_;
  std::optional<std::string> state_;
  std::optional<bool> can_request_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraCryptoKeyOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraCryptoKeyOptions();

  // Constructs an object setting all fields.
  explicit NexoraCryptoKeyOptions(
    const std::string* alias,
    const bool* require_biometric,
    const bool* use_strong_box);

  const std::string* alias() const;
  void set_alias(const std::string_view* value_arg);
  void set_alias(std::string_view value_arg);

  const bool* require_biometric() const;
  void set_require_biometric(const bool* value_arg);
  void set_require_biometric(bool value_arg);

  const bool* use_strong_box() const;
  void set_use_strong_box(const bool* value_arg);
  void set_use_strong_box(bool value_arg);

  bool operator==(const NexoraCryptoKeyOptions& other) const;
  bool operator!=(const NexoraCryptoKeyOptions& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraCryptoKeyOptions FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> alias_;
  std::optional<bool> require_biometric_;
  std::optional<bool> use_strong_box_;
};


// Generated class from Pigeon that represents data sent in messages.
class NexoraAiResult {
 public:
  // Constructs an object setting all non-nullable fields.
  NexoraAiResult();

  // Constructs an object setting all fields.
  explicit NexoraAiResult(
    const std::string* label,
    const double* confidence,
    const ::flutter::EncodableMap* bounding_box,
    const std::string* recognized_text);

  const std::string* label() const;
  void set_label(const std::string_view* value_arg);
  void set_label(std::string_view value_arg);

  const double* confidence() const;
  void set_confidence(const double* value_arg);
  void set_confidence(double value_arg);

  const ::flutter::EncodableMap* bounding_box() const;
  void set_bounding_box(const ::flutter::EncodableMap* value_arg);
  void set_bounding_box(const ::flutter::EncodableMap& value_arg);

  const std::string* recognized_text() const;
  void set_recognized_text(const std::string_view* value_arg);
  void set_recognized_text(std::string_view value_arg);

  bool operator==(const NexoraAiResult& other) const;
  bool operator!=(const NexoraAiResult& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static NexoraAiResult FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class HardwareApi;
  friend class AudioApi;
  friend class LocationApi;
  friend class SensorApi;
  friend class BiometricsApi;
  friend class BluetoothApi;
  friend class SecureStorageApi;
  friend class SystemApi;
  friend class CryptoApi;
  friend class AiApi;
  friend class PigeonInternalCodecSerializer;
  std::optional<std::string> label_;
  std::optional<double> confidence_;
  std::optional<::flutter::EncodableMap> bounding_box_;
  std::optional<std::string> recognized_text_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class HardwareApi {
 public:
  HardwareApi(const HardwareApi&) = delete;
  HardwareApi& operator=(const HardwareApi&) = delete;
  virtual ~HardwareApi() {}
  virtual void StartCamera(
    int64_t width,
    int64_t height,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  virtual void StartCameraWithOptions(
    const NexoraCameraOptions& options,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  virtual void StopCamera(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetVisionMode(
    const VisionModeOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void RegisterCustomClassifier(
    const CustomClassifierOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetFlash(
    bool on,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetZoom(
    double level,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void FlipCamera(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void TakePhoto(
    const std::string* file_name,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void StartVideoRecording(
    const std::string* file_name,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void StopVideoRecording(std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void ApplyCameraFilterShader(
    const std::string& shader_type,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by HardwareApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `HardwareApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    HardwareApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    HardwareApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  HardwareApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class AudioApi {
 public:
  AudioApi(const AudioApi&) = delete;
  AudioApi& operator=(const AudioApi&) = delete;
  virtual ~AudioApi() {}
  virtual void StartAudio(
    const BasicAudioOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StartAudioWithOptions(
    const NexoraAudioOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StopAudio(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void RouteAudioOutput(
    const std::string& route,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void GetAudioVolume(std::function<void(ErrorOr<double> reply)> result) = 0;
  virtual void SetAudioVolume(
    double level,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SelectAudioInput(
    const std::string& device,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetAudioGain(
    double gain,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by AudioApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `AudioApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AudioApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AudioApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  AudioApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class LocationApi {
 public:
  LocationApi(const LocationApi&) = delete;
  LocationApi& operator=(const LocationApi&) = delete;
  virtual ~LocationApi() {}
  virtual void StartLocation(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StartLocationWithOptions(
    const NexoraLocationOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StopLocation(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetBackgroundLocationEnabled(
    bool enabled,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by LocationApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `LocationApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    LocationApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    LocationApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  LocationApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class SensorApi {
 public:
  SensorApi(const SensorApi&) = delete;
  SensorApi& operator=(const SensorApi&) = delete;
  virtual ~SensorApi() {}
  virtual void StartSensor(
    int64_t frequency_hz,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StartSensorWithOptions(
    const NexoraSensorOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StopSensor(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void EnableDeadReckoning(
    bool enabled,
    std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by SensorApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `SensorApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    SensorApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    SensorApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  SensorApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class BiometricsApi {
 public:
  BiometricsApi(const BiometricsApi&) = delete;
  BiometricsApi& operator=(const BiometricsApi&) = delete;
  virtual ~BiometricsApi() {}
  virtual void Authenticate(
    const std::string& reason,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void AuthenticateWithOptions(
    const NexoraBiometricOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void CanAuthenticate(std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by BiometricsApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `BiometricsApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    BiometricsApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    BiometricsApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  BiometricsApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class BluetoothApi {
 public:
  BluetoothApi(const BluetoothApi&) = delete;
  BluetoothApi& operator=(const BluetoothApi&) = delete;
  virtual ~BluetoothApi() {}
  virtual void StartBluetoothScan(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StartBluetoothScanWithOptions(
    const NexoraBluetoothScanOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StopBluetoothScan(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void ConnectDevice(
    const std::string& id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void DisconnectDevice(
    const std::string& id,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void DiscoverServices(
    const std::string& device_id,
    std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  virtual void SendData(
    const std::string& device_id,
    const std::string& service_id,
    const std::string& char_id,
    const ::flutter::EncodableList& data,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void ReadData(
    const std::string& device_id,
    const std::string& service_id,
    const std::string& char_id,
    std::function<void(ErrorOr<std::optional<std::vector<uint8_t>>> reply)> result) = 0;
  virtual void SubscribeToCharacteristic(
    const std::string& device_id,
    const std::string& service_id,
    const std::string& char_id,
    bool enable,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void RequestMtu(
    const std::string& device_id,
    int64_t mtu,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StartBlePeripheral(
    const std::string& uuid,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StopBlePeripheral(std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by BluetoothApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `BluetoothApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    BluetoothApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    BluetoothApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  BluetoothApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class SecureStorageApi {
 public:
  SecureStorageApi(const SecureStorageApi&) = delete;
  SecureStorageApi& operator=(const SecureStorageApi&) = delete;
  virtual ~SecureStorageApi() {}
  virtual void GetStorageInfo(std::function<void(ErrorOr<std::optional<NexoraStorageInfo>> reply)> result) = 0;
  virtual void WriteFile(
    const std::string& file_name,
    const std::string& content,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void AppendFile(
    const std::string& file_name,
    const std::string& content,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void ReadFile(
    const std::string& file_name,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void DeleteFile(
    const std::string& file_name,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void FileExists(
    const std::string& file_name,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void ListFiles(std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  virtual void WriteBytes(
    const std::string& file_name,
    const std::vector<uint8_t>& bytes,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void ReadBytes(
    const std::string& file_name,
    std::function<void(ErrorOr<std::optional<std::vector<uint8_t>>> reply)> result) = 0;
  virtual void ClearCache(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void GetAppDirectory(std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void GetCacheDirectory(std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void GetExternalDirectory(std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;

  // The codec used by SecureStorageApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `SecureStorageApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    SecureStorageApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    SecureStorageApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  SecureStorageApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class SystemApi {
 public:
  SystemApi(const SystemApi&) = delete;
  SystemApi& operator=(const SystemApi&) = delete;
  virtual ~SystemApi() {}
  virtual void ConfigureSdk(
    const NexoraSdkConfig& config,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void RequestPermissions(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void RequestPermission(
    const std::string& type,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void GetPermissionStatus(
    const std::string& type,
    std::function<void(ErrorOr<NexoraPermissionStatus> reply)> result) = 0;
  virtual void OpenAppSettings(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void GetDeviceInfo(std::function<void(ErrorOr<NexoraDeviceInfo> reply)> result) = 0;
  virtual void GetConnectivityInfo(std::function<void(ErrorOr<NexoraConnectivityInfo> reply)> result) = 0;
  virtual void GetBatteryInfo(std::function<void(ErrorOr<std::optional<NexoraBatteryInfo>> reply)> result) = 0;
  virtual void GetWifiInfo(std::function<void(ErrorOr<std::optional<NexoraWifiInfo>> reply)> result) = 0;
  virtual void Vibrate(
    int64_t duration_ms,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void HapticFeedback(
    const std::string& type,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void PerformHapticWithOptions(
    const NexoraHapticOptions& options,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void CopyText(
    const std::string& text,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void PasteText(std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void OpenUrl(
    const std::string& url,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void ShareText(
    const std::string& text,
    const std::string* subject,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SaveToGallery(
    const std::string& file_path,
    std::function<void(ErrorOr<std::optional<std::string>> reply)> result) = 0;
  virtual void EnterPictureInPicture(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void GetConnectedUsbDevices(std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  virtual void StartForegroundService(
    const std::string& title,
    const std::string& content,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void UpdateForegroundService(
    const std::string& title,
    const std::string& text,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StopForegroundService(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void EnableSmartSync(
    const std::string& upload_endpoint_url,
    const ::flutter::EncodableMap& headers,
    int64_t roll_limit_bytes,
    bool require_wifi,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SetEcoModeEnabled(
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void IsEcoModeActive(std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void GetThermalState(std::function<void(ErrorOr<std::string> reply)> result) = 0;
  virtual void StartBackgroundSync(
    int64_t interval_minutes,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void StopBackgroundSync(std::function<void(ErrorOr<bool> reply)> result) = 0;

  // The codec used by SystemApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `SystemApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    SystemApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    SystemApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  SystemApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class CryptoApi {
 public:
  CryptoApi(const CryptoApi&) = delete;
  CryptoApi& operator=(const CryptoApi&) = delete;
  virtual ~CryptoApi() {}
  virtual void GenerateBiometricKey(
    const NexoraCryptoKeyOptions& options,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void DeleteKey(
    const std::string& alias,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void KeyExists(
    const std::string& alias,
    std::function<void(ErrorOr<bool> reply)> result) = 0;
  virtual void SignWithBiometricKey(
    const std::string& alias,
    const std::vector<uint8_t>& data,
    std::function<void(ErrorOr<std::optional<std::vector<uint8_t>>> reply)> result) = 0;
  virtual void EncryptWithBiometricKey(
    const std::string& alias,
    const std::vector<uint8_t>& plaintext,
    std::function<void(ErrorOr<std::optional<std::vector<uint8_t>>> reply)> result) = 0;
  virtual void DecryptWithBiometricKey(
    const std::string& alias,
    const std::vector<uint8_t>& ciphertext,
    std::function<void(ErrorOr<std::optional<std::vector<uint8_t>>> reply)> result) = 0;

  // The codec used by CryptoApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `CryptoApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    CryptoApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    CryptoApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  CryptoApi() = default;
};
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class AiApi {
 public:
  AiApi(const AiApi&) = delete;
  AiApi& operator=(const AiApi&) = delete;
  virtual ~AiApi() {}
  virtual void ProcessImageWithFaceDetection(
    const std::vector<uint8_t>& image_bytes,
    std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  virtual void ProcessImageWithBarcodeScanning(
    const std::vector<uint8_t>& image_bytes,
    std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  virtual void ProcessImageWithTextRecognition(
    const std::vector<uint8_t>& image_bytes,
    std::function<void(ErrorOr<::flutter::EncodableList> reply)> result) = 0;
  virtual void RunCustomModelInference(
    const std::string& model_path,
    const std::vector<uint8_t>& input_bytes,
    std::function<void(ErrorOr<std::optional<::flutter::EncodableMap>> reply)> result) = 0;

  // The codec used by AiApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `AiApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AiApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    AiApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  AiApi() = default;
};
}  // namespace nexora_sdk
#endif  // PIGEON_HARDWARE_API_G_H_
