name: nexora_sdk_android
description: The Android implementation of nexora_sdk.
version: 3.4.0
homepage: https://github.com/sahil8822/my_hardware_plugin
repository: https://github.com/sahil8822/my_hardware_plugin/tree/master/packages/nexora_sdk_android

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: nexora_sdk
    platforms:
      android:
        package: com.nexora.sdk
        pluginClass: NexoraSdk

dependencies:
  flutter:
    sdk: flutter
  nexora_sdk_platform_interface: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
