name: nexora_sdk_desktop
description: The desktop implementation of nexora_sdk.
version: 3.4.0
homepage: https://github.com/sahil8822/my_hardware_plugin
repository: https://github.com/sahil8822/my_hardware_plugin/tree/master/packages/nexora_sdk_desktop

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    implements: nexora_sdk
    platforms:
      macos:
        dartPluginClass: NexoraSdkDesktop
        fileName: nexora_sdk_desktop.dart
      windows:
        dartPluginClass: NexoraSdkDesktop
        fileName: nexora_sdk_desktop.dart
      linux:
        dartPluginClass: NexoraSdkDesktop
        fileName: nexora_sdk_desktop.dart

dependencies:
  flutter:
    sdk: flutter
  nexora_sdk_platform_interface:
    path: ../nexora_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
