// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsHardwareApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashHardwareApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsHardwareApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsHardwareApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsHardwareApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsHardwareApi(lhsKey, rhsKey) {
          if deepEqualsHardwareApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsHardwareApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashHardwareApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashHardwareApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashHardwareApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashHardwareApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashHardwareApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashHardwareApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct BasicCameraOptions: Hashable {
  var enableFlash: Bool? = nil
  var resolution: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BasicCameraOptions? {
    let enableFlash: Bool? = nilOrValue(pigeonVar_list[0])
    let resolution: String? = nilOrValue(pigeonVar_list[1])

    return BasicCameraOptions(
      enableFlash: enableFlash,
      resolution: resolution
    )
  }
  func toList() -> [Any?] {
    return [
      enableFlash,
      resolution,
    ]
  }
  static func == (lhs: BasicCameraOptions, rhs: BasicCameraOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.enableFlash, rhs.enableFlash) && deepEqualsHardwareApi(lhs.resolution, rhs.resolution)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BasicCameraOptions")
    deepHashHardwareApi(value: enableFlash, hasher: &hasher)
    deepHashHardwareApi(value: resolution, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct StartCameraResult: Hashable {
  var textureId: Int64? = nil
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartCameraResult? {
    let textureId: Int64? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])

    return StartCameraResult(
      textureId: textureId,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      textureId,
      error,
    ]
  }
  static func == (lhs: StartCameraResult, rhs: StartCameraResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.textureId, rhs.textureId) && deepEqualsHardwareApi(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("StartCameraResult")
    deepHashHardwareApi(value: textureId, hasher: &hasher)
    deepHashHardwareApi(value: error, hasher: &hasher)
  }
}

private class HardwareApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BasicCameraOptions.fromList(self.readValue() as! [Any?])
    case 130:
      return StartCameraResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HardwareApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BasicCameraOptions {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? StartCameraResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HardwareApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HardwareApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HardwareApiPigeonCodecWriter(data: data)
  }
}

class HardwareApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HardwareApiPigeonCodec(readerWriter: HardwareApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HardwareApi {
  func startCamera(options: BasicCameraOptions) throws -> StartCameraResult
  func stopCamera() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HardwareApiSetup {
  static var codec: FlutterStandardMessageCodec { HardwareApiPigeonCodec.shared }
  /// Sets up an instance of `HardwareApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HardwareApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nexora_sdk_platform_interface.HardwareApi.startCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! BasicCameraOptions
        do {
          let result = try api.startCamera(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startCameraChannel.setMessageHandler(nil)
    }
    let stopCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nexora_sdk_platform_interface.HardwareApi.stopCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopCameraChannel.setMessageHandler { _, reply in
        do {
          try api.stopCamera()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopCameraChannel.setMessageHandler(nil)
    }
  }
}
